In [1]:
import numpy as np
from matplotlib.pyplot import axis

np.__version__

'2.4.2'

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("arr: ")
print(arr)
print("data type: ", arr.dtype)
print("dimension: ", arr.ndim)
print("number of elements: ", arr.size)
print("size: ", arr.shape)

arr: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
data type:  int64
dimension:  2
number of elements:  9
size:  (3, 3)


In [3]:
# generate an array with 5 elements of 0
arr_0 = np.zeros(5, dtype=int)
print("arr_0: ")
print(arr_0)

arr_0: 
[0 0 0 0 0]


In [4]:
# generate a 2-dimension (2 rows, 3 columns) array (matrix (2,3)), with data type float and has 6 elements of 1s
arr_1 = np.ones((2,3), dtype=float)
print("arr_1: ")
print(arr_1)

arr_1: 
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# generate a matrix 3x3 (3 rows, 3 columns) with element 1.42
arr_142 = np.full((3,3), 1.42)
print("arr_142: ")
print(arr_142)

arr_142: 
[[1.42 1.42 1.42]
 [1.42 1.42 1.42]
 [1.42 1.42 1.42]]


In [6]:
# generate an array that starts with 0 and ends with 10, step is 2
arr_4 = np.arange(0,10,2)
print("arr_4: ")
print(arr_4)

arr_4: 
[0 2 4 6 8]


In [7]:
# generate an array that hs 5 elements, starts with 0 and ends with 1
arr_5 = np.linspace(0,1,5)
print("arr_5: ")
print(arr_5)

arr_5: 
[0.   0.25 0.5  0.75 1.  ]


In [8]:
# generate a random matrix 2x2
arr_6 = np.random.random((2,2))
print("arr_6: ")
print(arr_6)

arr_6: 
[[0.23130135 0.60244643]
 [0.29413182 0.00845379]]


In [9]:
# generate a matrix 2x2 with normal distribution
arr_7 = np.random.normal(0,1,(2,2))
print("arr_7: ")
print(arr_7)

arr_7: 
[[-1.44433451 -0.11789138]
 [-0.79633877 -0.63859351]]


In [10]:
# generate a matrix 3x3 with int values in interval (0, 100)
arr_8 = np.random.randint(0,100,(3,3))
print("arr_8: ")
print(arr_8)


arr_8: 
[[53 38 27]
 [83 79 52]
 [93 15 88]]


In [11]:
# generate a unit matrix 3x3
arr_9 = np.eye(3,3)
print("arr_9: ")
print(arr_9)

arr_9: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# generate an array and print the 3. element out
arr_10 = np.random.random(6)
print("arr_10: ")
print(arr_10)
print(arr_10[2])

arr_10: 
[0.70091298 0.19330293 0.99433787 0.14413847 0.76043029 0.21609056]
0.9943378685693172


In [13]:
# generate a matrix 3x3, the elements are in the interval (-5,5). Print the element at the position [1,1]
matr = np.random.randint(-5,5,(3,3))
print("matr: ")
print(matr)
print(matr[1,1])

matr: 
[[ 4  2 -2]
 [-5 -5  3]
 [-1  3  3]]
-5


In [14]:
# print the first two rows and two columns out

arr_11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr_11: ")
print(arr_11)
print("arr_11 with the first two rows and two columns: ")
print(arr_11[:2,:2])


arr_11: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_11 with the first two rows and two columns: 
[[1 2]
 [4 5]]


In [15]:
# print the first row out
print(arr_11[0,:])

[1 2 3]


In [16]:
# print the 2. column out
print(arr_11[:,1])

[2 5 8]


In [17]:
# change elements of the array
arr_11_sub = arr_11[:2,:2]
print("arr_11_sub: ")
print(arr_11_sub)
arr_11_sub[0,0] = 99
print("arr_11_sub new: ")
print(arr_11_sub)
print("arr_11: ")
print(arr_11)

arr_11_sub: 
[[1 2]
 [4 5]]
arr_11_sub new: 
[[99  2]
 [ 4  5]]
arr_11: 
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [18]:
# copy() method

arr_11_copy = arr_11[:2,:2].copy()
print("arr_11_copy: ")
print(arr_11_copy)
arr_11_copy[0,0] = 555
print("arr_11_copy new: ")
print(arr_11_copy)
print("arr_11: ")
print(arr_11)

arr_11_copy: 
[[99  2]
 [ 4  5]]
arr_11_copy new: 
[[555   2]
 [  4   5]]
arr_11: 
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [19]:
# change shape of array

# generate an array with values from 1 to 6
arr = np.arange(1, 7)
print(arr)

# change shape of the array with reshape (2x3) but not save the new shape
arr.reshape((2,3))
#print(arr)

[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# change shape of the array with reshape (2x3) but save the new shape
arr.shape=(2,3)
print("arr: ")
print(arr)

arr: 
[[1 2 3]
 [4 5 6]]


In [21]:
# combine arrays with concatenate(), vstask(), hstask()

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

print(np.concatenate((arr_1,arr_2), axis=0))

[1 2 3 4 5 6]


In [22]:
np.vstack((arr_1,arr_2)) # stack arrays vertically (row wise), axis = 0

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.hstack((arr_1,arr_2)) # stack array horizontally (column wise), axis = 1

array([1, 2, 3, 4, 5, 6])

In [24]:
a = np.zeros((2,3), dtype=int)
b = np.ones((2,3), dtype =int)
np.concatenate([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
# axis = 1, then arrange the columns side by side
np.concatenate([a,b], axis= 1)

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [26]:
np.vstack([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
np.hstack([a,b])

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [28]:
x = np.array([1,1,1,2,2,3,3,3])
x1, x2, x3 = np.split(x, [2,5]) #2.5 is the index of the element at which the array splits.
print(x1,x2,x3, sep = ' ')

[1 1] [1 2 2] [3 3 3]


In [29]:
# reshape vector 9 elements into a matrix 3x3
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
# Split matrix mat into a row vector and a 2x3 matrix
vec, matrix = np.vsplit(mat, [1])
print(vec, matrix, sep = ', \n')

[[0 1 2]], 
[[3 4 5]
 [6 7 8]]


In [31]:
# Split matrix mat into a column vector and a 3x2 matrix
matrix, vec = np.hsplit(mat, [2])
print(matrix, vec, sep = ', \n')


[[0 1]
 [3 4]
 [6 7]], 
[[2]
 [5]
 [8]]


In [32]:
# sort elements in an array with np.sort() in ascending order
arr = np.array([2,1,-4,-2,5,3])
print("arr: ", arr)

arr:  [ 2  1 -4 -2  5  3]


In [33]:
# sort in ascending order
print("arr sorted ASC: ", np.sort(arr))

arr sorted ASC:  [-4 -2  1  2  3  5]


In [34]:
# sort index of elements in order
print("Index of elements in order: ", np.argsort(arr))

Index of elements in order:  [2 3 1 0 5 4]


In [35]:
# sort elements in rows and columns

arr = np.random.randint(0,100, (3,3))

print("arr: ")
print(arr)
print("arr sorted ASC in rows: ")
print(np.sort(arr, axis=0))
print("arr sorted ASC in columns: ")
print(np.sort(arr, axis=1))


arr: 
[[20 48 36]
 [68  2 93]
 [39 79 43]]
arr sorted ASC in rows: 
[[20  2 36]
 [39 48 43]
 [68 79 93]]
arr sorted ASC in columns: 
[[20 36 48]
 [ 2 68 93]
 [39 43 79]]


In [36]:
# Sort by parts with np.partition(<array>,<k>)
# returns an array of k elements, the smallest element on the left, the rest on the right, in any order

arr = np.random.randint(0,20, (1,8))
print("arr: ")
print(arr)
np.partition(arr,4)

arr: 
[[ 1 11  9  1  3  1  7  3]]


array([[ 1,  1,  1,  3,  3,  7,  9, 11]], dtype=int32)

In [37]:
# read and save file
data = np.random.randint(0,20, (3,3))
print("data: ")
print(data)
np.save("saved_data.npy", data)

data: 
[[ 6 14 17]
 [16 18 12]
 [10 17  4]]


In [38]:
# read file
loaded_file = np.load("saved_data.npy")
loaded_file

array([[ 6, 14, 17],
       [16, 18, 12],
       [10, 17,  4]], dtype=int32)

In [39]:
arr = np.arange(1,10,1)
print("arr: ", arr)
print("f1(x) = x*2: ", arr*2)
print("f2(x) = x^2: ", arr**2)
print("f3(x) = x^3: ", arr**3)
print("f4(x) = x%2: ", arr%2)

arr:  [1 2 3 4 5 6 7 8 9]
f1(x) = x*2:  [ 2  4  6  8 10 12 14 16 18]
f2(x) = x^2:  [ 1  4  9 16 25 36 49 64 81]
f3(x) = x^3:  [  1   8  27  64 125 216 343 512 729]
f4(x) = x%2:  [1 0 1 0 1 0 1 0 1]
