In [56]:
import numpy as np
from matplotlib.pyplot import axis

np.__version__

'2.4.2'

In [57]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("arr: ")
print(arr)
print("data type: ", arr.dtype)
print("dimension: ", arr.ndim)
print("number of elements: ", arr.size)
print("size: ", arr.shape)

arr: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
data type:  int64
dimension:  2
number of elements:  9
size:  (3, 3)


In [58]:
# generate an array with 5 elements of 0
arr_0 = np.zeros(5, dtype=int)
print("arr_0: ")
print(arr_0)

arr_0: 
[0 0 0 0 0]


In [59]:
# generate a 2-dimension (2 rows, 3 columns) array (matrix (2,3)), with data type float and has 6 elements of 1s
arr_1 = np.ones((2,3), dtype=float)
print("arr_1: ")
print(arr_1)

arr_1: 
[[1. 1. 1.]
 [1. 1. 1.]]


In [60]:
# generate a matrix 3x3 (3 rows, 3 columns) with element 1.42
arr_142 = np.full((3,3), 1.42)
print("arr_142: ")
print(arr_142)

arr_142: 
[[1.42 1.42 1.42]
 [1.42 1.42 1.42]
 [1.42 1.42 1.42]]


In [61]:
# generate an array that starts with 0 and ends with 10, step is 2
arr_4 = np.arange(0,10,2)
print("arr_4: ")
print(arr_4)

arr_4: 
[0 2 4 6 8]


In [62]:
# generate an array that hs 5 elements, starts with 0 and ends with 1
arr_5 = np.linspace(0,1,5)
print("arr_5: ")
print(arr_5)

arr_5: 
[0.   0.25 0.5  0.75 1.  ]


In [63]:
# generate a random matrix 2x2
arr_6 = np.random.random((2,2))
print("arr_6: ")
print(arr_6)

arr_6: 
[[0.37573558 0.53965732]
 [0.17772367 0.18617126]]


In [64]:
# generate a matrix 2x2 with normal distribution
arr_7 = np.random.normal(0,1,(2,2))
print("arr_7: ")
print(arr_7)

arr_7: 
[[ 0.54924254 -0.226422  ]
 [ 0.81329076 -0.86473146]]


In [65]:
# generate a matrix 3x3 with int values in interval (0, 100)
arr_8 = np.random.randint(0,100,(3,3))
print("arr_8: ")
print(arr_8)


arr_8: 
[[20 95  1]
 [18  6 35]
 [32  5 43]]


In [66]:
# generate a unit matrix 3x3
arr_9 = np.eye(3,3)
print("arr_9: ")
print(arr_9)

arr_9: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
# generate an array and print the 3. element out
arr_10 = np.random.random(6)
print("arr_10: ")
print(arr_10)
print(arr_10[2])

arr_10: 
[0.75688042 0.87822521 0.80906375 0.08361499 0.46543149 0.45756287]
0.8090637487762692


In [68]:
# generate a matrix 3x3, the elements are in the interval (-5,5). Print the element at the position [1,1]
matr = np.random.randint(-5,5,(3,3))
print("matr: ")
print(matr)
print(matr[1,1])

matr: 
[[-3 -5 -2]
 [ 3 -3 -5]
 [ 0  3 -1]]
-3


In [69]:
# print the first two rows and two columns out

arr_11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr_11: ")
print(arr_11)
print("arr_11 with the first two rows and two columns: ")
print(arr_11[:2,:2])


arr_11: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_11 with the first two rows and two columns: 
[[1 2]
 [4 5]]


In [70]:
# print the first row out
print(arr_11[0,:])

[1 2 3]


In [71]:
# print the 2. column out
print(arr_11[:,1])

[2 5 8]


In [72]:
# change elements of the array
arr_11_sub = arr_11[:2,:2]
print("arr_11_sub: ")
print(arr_11_sub)
arr_11_sub[0,0] = 99
print("arr_11_sub new: ")
print(arr_11_sub)
print("arr_11: ")
print(arr_11)

arr_11_sub: 
[[1 2]
 [4 5]]
arr_11_sub new: 
[[99  2]
 [ 4  5]]
arr_11: 
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [73]:
# copy() method

arr_11_copy = arr_11[:2,:2].copy()
print("arr_11_copy: ")
print(arr_11_copy)
arr_11_copy[0,0] = 555
print("arr_11_copy new: ")
print(arr_11_copy)
print("arr_11: ")
print(arr_11)

arr_11_copy: 
[[99  2]
 [ 4  5]]
arr_11_copy new: 
[[555   2]
 [  4   5]]
arr_11: 
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [77]:
# change shape of array

# generate an array with values from 1 to 6
arr = np.arange(1, 7)
print(arr)

# change shape of the array with reshape (2x3) but not save the new shape
arr.reshape((2,3))
#print(arr)

[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
# change shape of the array with reshape (2x3) but save the new shape
arr.shape=(2,3)
print("arr: ")
print(arr)

arr: 
[[1 2 3]
 [4 5 6]]


In [85]:
# combine arrays with concatenate(), vstask(), hstask()

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

print(np.concatenate((arr_1,arr_2), axis=0))

[1 2 3 4 5 6]


In [81]:
np.vstack((arr_1,arr_2)) # stack arrays vertically (row wise), axis = 0

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
np.hstack((arr_1,arr_2)) # stack array horizontally (column wise), axis = 1

array([1, 2, 3, 4, 5, 6])

In [83]:
a = np.zeros((2,3), dtype=int)
b = np.ones((2,3), dtype =int)
np.concatenate([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [86]:
# axis = 1, then arrange the columns side by side
np.concatenate([a,b], axis= 1)

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [87]:
np.vstack([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [88]:
np.hstack([a,b])

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [92]:
x = np.array([1,1,1,2,2,3,3,3])
x1, x2, x3 = np.split(x, [2,5]) #2.5 is the index of the element at which the array splits.
print(x1,x2,x3, sep = ' ')

[1 1] [1 2 2] [3 3 3]


In [93]:
# reshape vector 9 elements into a matrix 3x3
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [95]:
# Split matrix mat into a row vector and a 2x3 matrix
vec, matrix = np.vsplit(mat, [1])
print(vec, matrix, sep = ', \n')

[[0 1 2]], 
[[3 4 5]
 [6 7 8]]


In [97]:
# Split matrix mat into a column vector and a 3x2 matrix
matrix, vec = np.hsplit(mat, [2])
print(vec, matrix, sep = ', \n')


[[2]
 [5]
 [8]], 
[[0 1]
 [3 4]
 [6 7]]
